drop table if exists tarefa;
create table tarefa (
	Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao text NOT NULL,
    categoria int NOT NULL,
    concluido boolean NOT NULL
);
insert into tarefa (descricao, categoria, concluido) values ('Tarefa 1', 0, true), ('Tarefa 2', 1, true), ('Tarefa 3', 2, false), ('Tarefa 4', 3, false);